export const MOCK_FOOD_DB = [
  {
    title: 'Libové Masa',
    foodList: [
      {
        title: 'Kuřecí Prso',
        category: 'Maso',
        nutrition: {
          calories: 142,
          macro: {
            protein: 26.7,
            carbohydrate: 0,
            sugar: 0,
            fiber: 0,
            totalFat: 3.1,
            saturatedFat: 0.9,
            monounsaturatedFat: 1.1,
            polyunsaturatedFat: 0.7,
            transFat: 0.1,
            cholesterol: 73,
          },
          minerals: {
            sodium: 74,
            calcium: 13,
            potassium: 220,
            magnesium: 29,
            iron: 1,
          },
          vitamins: {
            vitaminA: 6.8,
            vitaminB: 0.3,
            vitaminC: 0,
            vitaminD: 0.11,
            vitaminE: 0.31,
            vitaminK: 0.34,
          },
        },
        imgSrc:
          'https://www.rohlik.cz/cdn-cgi/image/f=auto,w=500,h=500/https://cdn.rohlik.cz/images/grocery/products/1307145/1307145-1532681017.jpg',
      },
      {
        title: 'Krutí Prso',
        category: 'Maso',
        nutrition: {
          calories: 0,
          macro: {
            protein: 0,
            carbohydrate: 0,
            sugar: 0,
            fiber: 0,
            totalFat: 0,
            saturatedFat: 0,
            monounsaturatedFat: 0,
            polyunsaturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
          },
          minerals: {
            sodium: 0,
            calcium: 0,
            potassium: 0,
            magnesium: 0,
            iron: 0,
          },
          vitamins: {
            vitaminA: 0,
            vitaminB: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            vitaminK: 0,
          },
        },
        imgSrc:
          'https://www.rohlik.cz/cdn-cgi/image/f=auto,w=500,h=500/https://cdn.rohlik.cz/images/grocery/products/1353733/1353733-1582105345.jpg',
      },
      {
        title: 'Vepřová Panenka',
        category: 'Maso',
        nutrition: {
          calories: 0,
          macro: {
            protein: 0,
            carbohydrate: 0,
            sugar: 0,
            fiber: 0,
            totalFat: 0,
            saturatedFat: 0,
            monounsaturatedFat: 0,
            polyunsaturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
          },
          minerals: {
            sodium: 0,
            calcium: 0,
            potassium: 0,
            magnesium: 0,
            iron: 0,
          },
          vitamins: {
            vitaminA: 0,
            vitaminB: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            vitaminK: 0,
          },
        },
        imgSrc: 'https://data.labuznik.cz/labuznik/images/640x480/14445.jpg?3',
      },
      {
        title: 'Hovězí Panenka',
        category: 'Maso',
        nutrition: {
          calories: 0,
          macro: {
            protein: 0,
            carbohydrate: 0,
            sugar: 0,
            fiber: 0,
            totalFat: 0,
            saturatedFat: 0,
            monounsaturatedFat: 0,
            polyunsaturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
          },
          minerals: {
            sodium: 0,
            calcium: 0,
            potassium: 0,
            magnesium: 0,
            iron: 0,
          },
          vitamins: {
            vitaminA: 0,
            vitaminB: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            vitaminK: 0,
          },
        },
        imgSrc:
          'https://embed.widencdn.net/img/beef/wa7zkwrlc1/800x600px/Tenderloin%20Roast_Chateaubriand.psd?keep=c&u=7fueml',
      },
    ],
  },
  {
    title: 'Tučné Ryby',
    foodList: [
      {
        title: 'Losos',
        category: 'Tučné Ryby',
        nutrition: {
          calories: 0,
          macro: {
            protein: 0,
            carbohydrate: 0,
            sugar: 0,
            fiber: 0,
            totalFat: 0,
            saturatedFat: 0,
            monounsaturatedFat: 0,
            polyunsaturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
          },
          minerals: {
            sodium: 0,
            calcium: 0,
            potassium: 0,
            magnesium: 0,
            iron: 0,
          },
          vitamins: {
            vitaminA: 0,
            vitaminB: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            vitaminK: 0,
          },
        },
        imgSrc:
          'https://www.svetbedynek.cz/userfiles_cs/product-images/2670/94d3a9ef8e931aed7dead1f34915699d.jpg',
      },
      {
        title: 'Tuňák',
        category: 'Tučné Ryby',
        nutrition: {
          calories: 0,
          macro: {
            protein: 0,
            carbohydrate: 0,
            sugar: 0,
            fiber: 0,
            totalFat: 0,
            saturatedFat: 0,
            monounsaturatedFat: 0,
            polyunsaturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
          },
          minerals: {
            sodium: 0,
            calcium: 0,
            potassium: 0,
            magnesium: 0,
            iron: 0,
          },
          vitamins: {
            vitaminA: 0,
            vitaminB: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            vitaminK: 0,
          },
        },
        imgSrc:
          'https://www.rohlik.cz/cdn-cgi/image/f=auto,w=500,h=500/https://cdn.rohlik.cz/images/grocery/products/1347509/1347509-1542704557.jpg',
      },
      {
        title: 'Sardinky',
        category: 'Tučné Ryby',
        nutrition: {
          calories: 0,
          macro: {
            protein: 0,
            carbohydrate: 0,
            sugar: 0,
            fiber: 0,
            totalFat: 0,
            saturatedFat: 0,
            monounsaturatedFat: 0,
            polyunsaturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
          },
          minerals: {
            sodium: 0,
            calcium: 0,
            potassium: 0,
            magnesium: 0,
            iron: 0,
          },
          vitamins: {
            vitaminA: 0,
            vitaminB: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            vitaminK: 0,
          },
        },
        imgSrc:
          'https://cdn.myshoptet.com/usr/www.cerstveryby.cz/user/shop/big/2087_sardine3.jpg?5be6f478',
      },
    ],
  },
  {
    title: 'Zeleniny',
    foodList: [
      {
        title: 'Brokolice',
        category: 'Zeleniny',
        nutrition: {
          calories: 0,
          macro: {
            protein: 0,
            carbohydrate: 0,
            sugar: 0,
            fiber: 0,
            totalFat: 0,
            saturatedFat: 0,
            monounsaturatedFat: 0,
            polyunsaturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
          },
          minerals: {
            sodium: 0,
            calcium: 0,
            potassium: 0,
            magnesium: 0,
            iron: 0,
          },
          vitamins: {
            vitaminA: 0,
            vitaminB: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            vitaminK: 0,
          },
        },
        imgSrc:
          'https://image.freepik.com/free-photo/fresh-broccoli-blocks-cooking-isolated-white-background_33736-2451.jpg',
      },
      {
        title: 'Mrkev',
        category: 'Zeleniny',
        nutrition: {
          calories: 0,
          macro: {
            protein: 0,
            carbohydrate: 0,
            sugar: 0,
            fiber: 0,
            totalFat: 0,
            saturatedFat: 0,
            monounsaturatedFat: 0,
            polyunsaturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
          },
          minerals: {
            sodium: 0,
            calcium: 0,
            potassium: 0,
            magnesium: 0,
            iron: 0,
          },
          vitamins: {
            vitaminA: 0,
            vitaminB: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            vitaminK: 0,
          },
        },
        imgSrc: 'https://5.imimg.com/data5/QU/CV/MY-6171882/carrot-500x500.jpg',
      },
      {
        title: 'Sladká Brambora',
        category: 'Zeleniny',
        nutrition: {
          calories: 0,
          macro: {
            protein: 0,
            carbohydrate: 0,
            sugar: 0,
            fiber: 0,
            totalFat: 0,
            saturatedFat: 0,
            monounsaturatedFat: 0,
            polyunsaturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
          },
          minerals: {
            sodium: 0,
            calcium: 0,
            potassium: 0,
            magnesium: 0,
            iron: 0,
          },
          vitamins: {
            vitaminA: 0,
            vitaminB: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            vitaminK: 0,
          },
        },
        imgSrc:
          'https://www.rohlik.cz/cdn-cgi/image/f=auto,w=500,h=500/https://cdn.rohlik.cz/images/grocery/products/1350677/1350677-1567345962.jpg',
      },
      {
        title: 'Brambora',
        category: 'Zeleniny',
        nutrition: {
          calories: 0,
          macro: {
            protein: 0,
            carbohydrate: 0,
            sugar: 0,
            fiber: 0,
            totalFat: 0,
            saturatedFat: 0,
            monounsaturatedFat: 0,
            polyunsaturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
          },
          minerals: {
            sodium: 0,
            calcium: 0,
            potassium: 0,
            magnesium: 0,
            iron: 0,
          },
          vitamins: {
            vitaminA: 0,
            vitaminB: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            vitaminK: 0,
          },
        },
        imgSrc:
          'https://www.rohlik.cz/cdn-cgi/image/f=auto,w=500,h=500/https://cdn.rohlik.cz/images/grocery/products/1326173/1326173-1528784439.jpg',
      },
      {
        title: 'Lilek',
        category: 'Zeleniny',
        nutrition: {
          calories: 0,
          macro: {
            protein: 0,
            carbohydrate: 0,
            sugar: 0,
            fiber: 0,
            totalFat: 0,
            saturatedFat: 0,
            monounsaturatedFat: 0,
            polyunsaturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
          },
          minerals: {
            sodium: 0,
            calcium: 0,
            potassium: 0,
            magnesium: 0,
            iron: 0,
          },
          vitamins: {
            vitaminA: 0,
            vitaminB: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            vitaminK: 0,
          },
        },
        imgSrc:
          'https://bloximages.chicago2.vip.townnews.com/thesouthern.com/content/tncms/assets/v3/editorial/e/63/e630fcfd-216a-54f0-9652-2eb1860ada14/5f57d16b9989f.image.jpg?resize=1200%2C1141',
      },
    ],
  },
  {
    title: 'Ovoce',
    foodList: [
      {
        title: 'Jablko',
        category: 'Ovoce',
        nutrition: {
          calories: 0,
          macro: {
            protein: 0,
            carbohydrate: 0,
            sugar: 0,
            fiber: 0,
            totalFat: 0,
            saturatedFat: 0,
            monounsaturatedFat: 0,
            polyunsaturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
          },
          minerals: {
            sodium: 0,
            calcium: 0,
            potassium: 0,
            magnesium: 0,
            iron: 0,
          },
          vitamins: {
            vitaminA: 0,
            vitaminB: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            vitaminK: 0,
          },
        },
        imgSrc:
          'https://image.freepik.com/free-photo/close-up-view-single-red-apple-isolated-white-background_69593-1575.jpg',
      },
      {
        title: 'Pomeranč',
        category: 'Ovoce',
        nutrition: {
          calories: 0,
          macro: {
            protein: 0,
            carbohydrate: 0,
            sugar: 0,
            fiber: 0,
            totalFat: 0,
            saturatedFat: 0,
            monounsaturatedFat: 0,
            polyunsaturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
          },
          minerals: {
            sodium: 0,
            calcium: 0,
            potassium: 0,
            magnesium: 0,
            iron: 0,
          },
          vitamins: {
            vitaminA: 0,
            vitaminB: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            vitaminK: 0,
          },
        },
        imgSrc:
          'https://www.ekofood.cz/fotky81864/fotos/_vyr_385_pomerance-z-farmy.jpg',
      },
      {
        title: 'Jahody',
        category: 'Ovoce',
        nutrition: {
          calories: 0,
          macro: {
            protein: 0,
            carbohydrate: 0,
            sugar: 0,
            fiber: 0,
            totalFat: 0,
            saturatedFat: 0,
            monounsaturatedFat: 0,
            polyunsaturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
          },
          minerals: {
            sodium: 0,
            calcium: 0,
            potassium: 0,
            magnesium: 0,
            iron: 0,
          },
          vitamins: {
            vitaminA: 0,
            vitaminB: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            vitaminK: 0,
          },
        },
        imgSrc: 'https://www.ordinace.cz/img/articles/16b9/jahody.jpg',
      },
      {
        title: 'Hroznové Víno',
        category: 'Ovoce',
        nutrition: {
          calories: 0,
          macro: {
            protein: 0,
            carbohydrate: 0,
            sugar: 0,
            fiber: 0,
            totalFat: 0,
            saturatedFat: 0,
            monounsaturatedFat: 0,
            polyunsaturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
          },
          minerals: {
            sodium: 0,
            calcium: 0,
            potassium: 0,
            magnesium: 0,
            iron: 0,
          },
          vitamins: {
            vitaminA: 0,
            vitaminB: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            vitaminK: 0,
          },
        },
        imgSrc:
          'https://m.actve.net/frekvence1/edee/clanky/23957/shutterstock_64629709-610x405.jpg',
      },
    ],
  },
  {
    title: 'Luštěniny',

    foodList: [
      {
        title: 'Červené Fazole',
        category: 'Luštěniny',
        nutrition: {
          calories: 0,
          macro: {
            protein: 0,
            carbohydrate: 0,
            sugar: 0,
            fiber: 0,
            totalFat: 0,
            saturatedFat: 0,
            monounsaturatedFat: 0,
            polyunsaturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
          },
          minerals: {
            sodium: 0,
            calcium: 0,
            potassium: 0,
            magnesium: 0,
            iron: 0,
          },
          vitamins: {
            vitaminA: 0,
            vitaminB: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            vitaminK: 0,
          },
        },
        imgSrc:
          'https://5.imimg.com/data5/JX/AB/MY-14534935/red-kidney-beans-500x500.jpg',
      },
      {
        title: 'Cizrna',
        category: 'Luštěniny',
        nutrition: {
          calories: 0,
          macro: {
            protein: 0,
            carbohydrate: 0,
            sugar: 0,
            fiber: 0,
            totalFat: 0,
            saturatedFat: 0,
            monounsaturatedFat: 0,
            polyunsaturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
          },
          minerals: {
            sodium: 0,
            calcium: 0,
            potassium: 0,
            magnesium: 0,
            iron: 0,
          },
          vitamins: {
            vitaminA: 0,
            vitaminB: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            vitaminK: 0,
          },
        },
        imgSrc: 'https://data.labuznik.cz/labuznik/images/640x480/14262.jpg?3',
      },
      {
        title: 'Čočka',
        category: 'Luštěniny',
        nutrition: {
          calories: 0,
          macro: {
            protein: 0,
            carbohydrate: 0,
            sugar: 0,
            fiber: 0,
            totalFat: 0,
            saturatedFat: 0,
            monounsaturatedFat: 0,
            polyunsaturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
          },
          minerals: {
            sodium: 0,
            calcium: 0,
            potassium: 0,
            magnesium: 0,
            iron: 0,
          },
          vitamins: {
            vitaminA: 0,
            vitaminB: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            vitaminK: 0,
          },
        },
        imgSrc: 'https://data.labuznik.cz/labuznik/images/640x480/14265.jpg?3',
      },
    ],
  },
  {
    title: 'Ořechy',

    foodList: [
      {
        title: 'Vlašské Ořechy',
        category: 'Ořechy',
        nutrition: {
          calories: 0,
          macro: {
            protein: 0,
            carbohydrate: 0,
            sugar: 0,
            fiber: 0,
            totalFat: 0,
            saturatedFat: 0,
            monounsaturatedFat: 0,
            polyunsaturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
          },
          minerals: {
            sodium: 0,
            calcium: 0,
            potassium: 0,
            magnesium: 0,
            iron: 0,
          },
          vitamins: {
            vitaminA: 0,
            vitaminB: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            vitaminK: 0,
          },
        },
        imgSrc:
          'https://www.vimcojim.cz/files/lide-ilustrace/2017%20obrazky/7.11.%20vlasky%20orech%20shutterstock_680681407_1000x667.jpg',
      },
      {
        title: 'Mandle',
        category: 'Ořechy',
        nutrition: {
          calories: 0,
          macro: {
            protein: 0,
            carbohydrate: 0,
            sugar: 0,
            fiber: 0,
            totalFat: 0,
            saturatedFat: 0,
            monounsaturatedFat: 0,
            polyunsaturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
          },
          minerals: {
            sodium: 0,
            calcium: 0,
            potassium: 0,
            magnesium: 0,
            iron: 0,
          },
          vitamins: {
            vitaminA: 0,
            vitaminB: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            vitaminK: 0,
          },
        },
        imgSrc: 'https://www.ochutnejorech.cz/obrazky/original/407.jpg',
      },
      {
        title: 'Pistácie',
        category: 'Ořechy',
        nutrition: {
          calories: 0,
          macro: {
            protein: 0,
            carbohydrate: 0,
            sugar: 0,
            fiber: 0,
            totalFat: 0,
            saturatedFat: 0,
            monounsaturatedFat: 0,
            polyunsaturatedFat: 0,
            transFat: 0,
            cholesterol: 0,
          },
          minerals: {
            sodium: 0,
            calcium: 0,
            potassium: 0,
            magnesium: 0,
            iron: 0,
          },
          vitamins: {
            vitaminA: 0,
            vitaminB: 0,
            vitaminC: 0,
            vitaminD: 0,
            vitaminE: 0,
            vitaminK: 0,
          },
        },
        imgSrc:
          'https://cdn.myshoptet.com/usr/www.nutiva.cz/user/shop/big/1625-2_pistacie-prazene-solene.jpg?5e9e82c0',
      },
    ],
  },

  // {
  //   title: 'Pečivo',
  //   foodList: [
  //     {
  //       title: 'Celozrné Housky',
  //       category: 'Pečivo',
  //       nutrition: {
  //         calories: 246,
  //         protein: 7,
  //         carbohydrate: 50,
  //         sugar: 2,
  //         totalFat: 1,
  //         saturatedFat: 0,
  //         monounsaturatedFat: 0,
  //         polyunsaturatedFat: 0,
  //         cholesterol: 0,
  //         fiber: 5,
  //         iron: 0,
  //         sodium: 0,
  //         calcium: 0,
  //         phe: 350,
  //       },
  //       imgSrc:
  //         'https://www.rohlik.cz/cdn-cgi/image/f=auto,w=500,h=500/https://cdn.rohlik.cz/images/grocery/products/717953/717953-1498808178.jpg',
  //     },
  //   ],
  // },
];
